name: wordle_solver
description: An easy to use Worldle solver, with support for a wide variety of word lengths

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_phoenix: ^1.0.0
  path_provider: ^2.0.10
  shared_preferences: ^2.0.13
  tuple: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  lint: ^1.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: ClearSans
      fonts:
        - asset: 'lib/fonts/Clear Sans/ClearSans-Bold.ttf'
        - asset: 'lib/fonts/Clear Sans/ClearSans-BoldItalic.ttf'
        - asset: 'lib/fonts/Clear Sans/ClearSans-Italic.ttf'
        - asset: 'lib/fonts/Clear Sans/ClearSans-Light.ttf'
        - asset: 'lib/fonts/Clear Sans/ClearSans-Medium.ttf'
        - asset: 'lib/fonts/Clear Sans/ClearSans-MediumItalic.ttf'
        - asset: 'lib/fonts/Clear Sans/ClearSans-Regular.ttf'
        - asset: 'lib/fonts/Clear Sans/ClearSans-Thin.ttf'
    - family: HelveticaNeue
      fonts:
        - asset: 'lib/fonts/Helvetica Neue/HelveticaNeue.ttf'
    - family: KarnakCondensed
      fonts:
        - asset: 'lib/fonts/Karnak Condensed/karnakcondensed-normal-700.ttf'
  assets:
    - lib/data/