name: wordle_solver
description: An easy to use Worldle solver, with support for a wide variety of word lengths

publish_to: 'none'

version: 1.0.1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_phoenix: ^1.0.0
  introduction_screen: ^3.0.2
  shared_preferences: ^2.0.13
  tuple: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  lint: ^1.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Butler
      fonts:
        - asset: 'lib/fonts/Butler/Butler_Regular.otf'
    - family: ClearSans
      fonts:
        - asset: 'lib/fonts/Clear Sans/ClearSans-Regular.ttf'
  assets:
    - lib/data/